"""Streamlit interface for industrial bottle anomaly detection."""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import streamlit as st
from PIL import Image
from tensorflow import keras

from anomaly_detection.preprocessing import prepare_pil_image
from anomaly_detection.scoring import compute_error_maps, image_scores_from_error_maps

DEFAULT_MODEL_PATH = Path("artifacts/best_autoencoder.keras")
DEFAULT_METADATA_PATH = Path("artifacts/metadata.json")


@st.cache_resource(show_spinner=False)
def load_model_from_path(path: str) -> keras.Model:
    """Load a Keras model once per Streamlit server process."""
    return keras.models.load_model(path, compile=False)


@st.cache_resource(show_spinner=False)
def load_model_from_bytes(model_bytes: bytes) -> keras.Model:
    """Load an uploaded .keras model through a temporary file."""
    with tempfile.NamedTemporaryFile(suffix=".keras") as temporary_file:
        temporary_file.write(model_bytes)
        temporary_file.flush()
        return keras.models.load_model(temporary_file.name, compile=False)


def read_default_metadata() -> dict[str, object]:
    if DEFAULT_METADATA_PATH.exists():
        return json.loads(DEFAULT_METADATA_PATH.read_text(encoding="utf-8"))
    return {}


def render_error_map(error_map: np.ndarray) -> plt.Figure:
    figure, axis = plt.subplots(figsize=(5, 5))
    image = axis.imshow(error_map, cmap="hot")
    axis.set_title("Reconstruction-error map")
    axis.axis("off")
    figure.colorbar(image, ax=axis, fraction=0.046, pad=0.04)
    figure.tight_layout()
    return figure


def main() -> None:
    st.set_page_config(
        page_title="MVTec Bottle Anomaly Detection",
        page_icon="🔍",
        layout="wide",
    )
    st.title("Industrial Bottle Anomaly Detection")
    st.caption(
        "A convolutional autoencoder trained only on defect-free MVTec AD bottle images."
    )

    metadata = read_default_metadata()

    with st.sidebar:
        st.header("Model configuration")
        uploaded_model = st.file_uploader("Upload a trained Keras model", type=["keras"])
        if uploaded_model is not None:
            with st.spinner("Loading uploaded model..."):
                model = load_model_from_bytes(uploaded_model.getvalue())
            st.success("Uploaded model loaded")
        elif DEFAULT_MODEL_PATH.exists():
            with st.spinner("Loading repository model..."):
                model = load_model_from_path(str(DEFAULT_MODEL_PATH))
            st.success("Repository model loaded")
        else:
            model = None
            st.info(
                "Add artifacts/best_autoencoder.keras or upload the model generated by scripts/train.py."
            )

        default_threshold = float(metadata.get("threshold", 0.01))
        threshold = st.number_input(
            "Anomaly threshold",
            min_value=0.0,
            value=default_threshold,
            format="%.6f",
            help="Use the threshold stored in artifacts/metadata.json after training.",
        )
        score_percentile = st.slider(
            "Pixel-error percentile",
            min_value=90.0,
            max_value=100.0,
            value=float(metadata.get("score_percentile", 99.9)),
            step=0.1,
        )

    if model is None:
        st.warning("A trained .keras model is required before inference can run.")
        st.stop()

    model_shape = model.input_shape
    if isinstance(model_shape, list):
        model_shape = model_shape[0]
    image_height, image_width = int(model_shape[1]), int(model_shape[2])

    uploaded_image = st.file_uploader(
        "Upload a bottle image",
        type=["bmp", "jpeg", "jpg", "png"],
    )
    if uploaded_image is None:
        st.info("Upload a normal or defective bottle image to inspect it.")
        st.stop()

    image = Image.open(uploaded_image).convert("RGB")
    batch = prepare_pil_image(image, image_size=(image_width, image_height))

    reconstruction = np.asarray(model.predict(batch, verbose=0), dtype=np.float32)
    error_map = compute_error_maps(batch, reconstruction)
    score = float(
        image_scores_from_error_maps(error_map, percentile=score_percentile)[0]
    )
    is_anomaly = score > threshold

    metric_col, decision_col = st.columns(2)
    metric_col.metric("Anomaly score", f"{score:.6f}")
    decision_col.metric("Decision", "ANOMALY" if is_anomaly else "NORMAL")

    if is_anomaly:
        st.error("The reconstruction score is above the calibrated threshold.")
    else:
        st.success("The reconstruction score is below the calibrated threshold.")

    original_col, reconstruction_col, error_col = st.columns(3)
    with original_col:
        st.subheader("Original")
        st.image(image, use_container_width=True)
    with reconstruction_col:
        st.subheader("Reconstruction")
        st.image(np.clip(reconstruction[0], 0.0, 1.0), clamp=True, use_container_width=True)
    with error_col:
        st.subheader("Localization")
        figure = render_error_map(error_map[0])
        st.pyplot(figure, use_container_width=True)
        plt.close(figure)

    with st.expander("How the score is calculated"):
        st.write(
            "The model reconstructs the uploaded image. A pixel-wise mean squared error map is "
            "computed across RGB channels. The selected high percentile of that map becomes the "
            "image-level anomaly score, which is compared with a threshold calibrated exclusively "
            "from normal validation images."
        )


if __name__ == "__main__":
    main()
